const Type = {
  SWITCH_THEME: 'SWITCH_THEME',
  CHANGE_CURRENT_INPUT: 'CHANGE_INPUT',
  CHANGE_CURRENT_OPREATOR: 'CHANGE_CURRENT_OPREATOR',
  PUSH_INPUT_AND_OPERATOR: 'PUSH_INPUT_AND_OPERATOR',
  CLEAR_ALL_INPUTS: 'CLEAR_INPUT',
  PUSH_RESULT: 'PUSH_RESULT',
  REMOVE_RESULT: 'PUSH_RESULT',
  CLEAR_RESULT_LIST: 'PUSH_RESULT',
};
export default Type;
